{% set name = "KiMoPack" %}
{% set version = "6.4.3" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 1624e9a9dc53cfa1a709a6a034cb04fb6c38fafa52e146a4a92011693f298de7

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python
  run:
    - python

about:
  home: The package home page
  license: "GNU General Public v3 (GPLv3)"
  license_family: GPL3
  license_file: 
  summary: "A comprehensive package for the analysis of kinetic data."
  doc_url: 
  dev_url: 

extra:
  recipe-maintainers:
    - your-github-id-here
